name: charts_common
version: 0.9.1
description: A common library for charting packages.
author: Charts Team <charts_flutter@google.com>
homepage: https://github.com/google/charts

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0
  intl: ^0.17.0
  logging: any
  meta: ^1.3.0
  vector_math: ^2.1.0

dev_dependencies:
  mockito: ^4.0.0
  test: ^1.5.3
